name: build

on: [push]

jobs:
  build:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for publish.sh
      run: chmod +x publish.sh
    - name: Build with Gradle
      run: ./gradlew $GRADLE_BUILD_OPTS build asciidoc --scan
    - name: Run publish if necessary
      env: # Or as an environment variable
        GRGIT_USER: ${{ secrets.GRGIT_USER }}
      run: ./publish.sh
